import { TeamLeader } from './types';

export const mockTeamLeaders: TeamLeader[] = [
  {
    id: '1',
    slug: 'jeremy-mcdonald',
    status: 'published',
    full_name: 'Jeremy McDonald',
    nmls_number: '1195266',
    email: 'jeremy@mcdonald-mtg.com',
    phone: '(904) 555-0100',
    headshot_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face',
    bio: 'With over 20 years in finance, I founded The Legends Mortgage Team to bring real expertise, honest guidance, and competitive rates to every client I serve in Northeast Florida. I believe buying a home should be exciting — not confusing — and my team is built around making that happen. Whether you\'re a first-time buyer, a veteran using your VA benefit, or an investor building your portfolio, I\'m here to find you the right loan at the right rate. I back that up with my $1,000 Lowest Rate and Fee Guarantee. Let\'s talk.',
    service_areas: ['Jacksonville FL', 'St. Augustine FL', 'Fleming Island FL', 'Orange Park FL', 'Ponte Vedra FL'],
    languages: ['English'],
    specialties: ['VA', 'FHA', 'Conventional', 'Jumbo', 'First-Time Buyer'],
    google_review_url: 'https://g.page/r/legends-mortgage',
    zillow_review_url: 'https://www.zillow.com/profile/jeremymcdonald',
    template_id: 'modern-professional',
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
  },
  {
    id: '2',
    slug: 'carlos-rivera',
    status: 'published',
    full_name: 'Carlos Rivera',
    nmls_number: '1234567',
    email: 'carlos.rivera@loanfactory.com',
    phone: '(904) 555-0101',
    headshot_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    bio: 'Helping Jacksonville\'s Spanish-speaking community achieve the dream of homeownership. I specialize in VA loans for our veterans and FHA loans for first-time buyers. Hablo español con fluidez — llámame y hablemos de tu futuro hogar.',
    service_areas: ['Jacksonville FL', 'Gainesville FL', 'Lake City FL'],
    languages: ['English', 'Spanish'],
    specialties: ['VA', 'FHA', 'First-Time Buyer'],
    google_review_url: 'https://g.page/r/carlos-rivera-mortgage',
    template_id: 'modern-professional',
    created_at: '2026-05-05T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
  },
  {
    id: '3',
    slug: 'mei-chen',
    status: 'published',
    full_name: 'Mei Chen',
    nmls_number: '2345678',
    email: 'mei.chen@loanfactory.com',
    phone: '(813) 555-0102',
    headshot_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
    bio: 'Serving Tampa Bay\'s Chinese-American community with expert mortgage guidance in English, Mandarin, and Cantonese. I specialize in Jumbo and Conventional loans for move-up buyers and investors. 我很乐意用普通话或粤语与您交流。',
    service_areas: ['Tampa FL', 'Clearwater FL', 'St. Petersburg FL', 'Brandon FL'],
    languages: ['English', 'Mandarin', 'Cantonese'],
    specialties: ['Jumbo', 'Conventional', 'First-Time Buyer'],
    zillow_review_url: 'https://www.zillow.com/profile/meichen',
    template_id: 'modern-professional',
    created_at: '2026-05-08T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
  },
  {
    id: '4',
    slug: 'nguyen-van-duc',
    status: 'published',
    full_name: 'Nguyen Van Duc',
    nmls_number: '3456789',
    email: 'duc.nguyen@loanfactory.com',
    phone: '(407) 555-0103',
    headshot_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    bio: 'Proud to serve Orlando\'s Vietnamese community as your trusted mortgage advisor. I specialize in FHA and USDA loans — programs that help families get into their first home with minimal down payment. Tôi rất vui được phục vụ cộng đồng người Việt tại Orlando.',
    service_areas: ['Orlando FL', 'Kissimmee FL', 'Sanford FL', 'Apopka FL'],
    languages: ['English', 'Vietnamese'],
    specialties: ['FHA', 'USDA', 'First-Time Buyer'],
    google_review_url: 'https://g.page/r/duc-nguyen-mortgage',
    template_id: 'modern-professional',
    created_at: '2026-05-10T00:00:00Z',
    updated_at: '2026-05-20T00:00:00Z',
  },
  {
    id: '5',
    slug: 'ana-martinez',
    status: 'pending_review',
    full_name: 'Ana Martinez',
    nmls_number: '4567890',
    email: 'ana.martinez@loanfactory.com',
    phone: '(305) 555-0104',
    headshot_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face',
    bio: 'Miami mortgage specialist serving the Latino community across South Florida. I make the homebuying process simple and stress-free — in English or Spanish.',
    service_areas: ['Miami FL', 'Hialeah FL', 'Coral Gables FL', 'Doral FL'],
    languages: ['English', 'Spanish'],
    specialties: ['FHA', 'Conventional', 'First-Time Buyer', 'VA'],
    template_id: 'modern-professional',
    created_at: '2026-05-18T00:00:00Z',
    updated_at: '2026-05-19T00:00:00Z',
  },
  {
    id: '6',
    slug: 'david-kim',
    status: 'draft',
    full_name: 'David Kim',
    nmls_number: '5678901',
    email: 'david.kim@loanfactory.com',
    phone: '(404) 555-0105',
    headshot_url: '',
    bio: 'Korean-speaking mortgage advisor serving Atlanta and surrounding areas.',
    service_areas: ['Atlanta GA', 'Duluth GA', 'Suwanee GA'],
    languages: ['English', 'Korean'],
    specialties: ['Conventional', 'Jumbo'],
    template_id: 'modern-professional',
    created_at: '2026-05-19T00:00:00Z',
    updated_at: '2026-05-19T00:00:00Z',
  },
];

export function getTeamLeaderBySlug(slug: string): TeamLeader | undefined {
  return mockTeamLeaders.find((tl) => tl.slug === slug);
}

export function getPublishedTeamLeaders(): TeamLeader[] {
  return mockTeamLeaders.filter((tl) => tl.status === 'published');
}
